Fix ACPI vs amdgpu 'BOOLEAN' typedef conflict
Currently there are preprocessor workarounds in amdgpu but they were erroring for me:

drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_pp_smu.c:945:48: error: incompatible pointer types assigning to 'enum pp_smu_status (*)(struct pp_smu *, bool)' (aka 'enum pp_smu_status (*)(struct pp_smu
 *, _Bool)') from 'enum pp_smu_status (struct pp_smu *, BOOLEAN)' (aka 'enum pp_smu_status (struct pp_smu *, unsigned char)') [-Werror,-Wincompatible-pointer-types]
                funcs->nv_funcs.set_pstate_handshake_support = pp_nv_set_pstate_handshake_support;